POST http://localhost:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "firstName":"buyer",
  "lastName":"buyer",
  "displayName":"buyer",
  "password":"buyer@gmail.com",
  "email":"buyer5@gmail.com",
  "role":"customer"
}